name: Kendi APK Projemiz

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Depodan Çek
      uses: actions/checkout@v4

    - name: Java JDK 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        # Hata veren cache özelliğini devre dışı bıraktık

    - name: Java UTF-8 Çözüm Ayarı
      run: echo "GRADLE_OPTS=-Dfile.encoding=utf-8" >> $GITHUB_ENV

    - name: Gradle Çalıştırma İzni Ver
      run: chmod +x ./gradlew

    - name: APK Derleme İşlemini Başlat
      run: ./gradlew clean assembleDebug

    - name: Hazır APK Dosyasını Çıktı Olarak Al (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Benim-Ozel-Uygulamam
        path: app/build/outputs/apk/debug/app-debug.apk
        
